#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TimeTable.Droid.Resource", IsApplication=true)]

namespace TimeTable.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_top = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_bottom = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon_big = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int locationpin = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int actionBarBtnAdd = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int actionBarBtnSettings = 2131099658;
			
			// aapt resource value: 0x7f060010
			public const int btnAddNewFavStation = 2131099664;
			
			// aapt resource value: 0x7f060013
			public const int btnTakeMeToSettings = 2131099667;
			
			// aapt resource value: 0x7f060001
			public const int container = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int departureTimeTextView = 2131099654;
			
			// aapt resource value: 0x7f06000d
			public const int editStationIdentifier = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int editStationNick = 2131099663;
			
			// aapt resource value: 0x7f060002
			public const int imgLocationIcon = 2131099650;
			
			// aapt resource value: 0x7f060011
			public const int listViewFavorites = 2131099665;
			
			// aapt resource value: 0x7f060007
			public const int minsUntilDepartureTimeTextView = 2131099655;
			
			// aapt resource value: 0x7f060015
			public const int refresher = 2131099669;
			
			// aapt resource value: 0x7f060008
			public const int routeDescTextView = 2131099656;
			
			// aapt resource value: 0x7f060016
			public const int routeDetailsListView = 2131099670;
			
			// aapt resource value: 0x7f060005
			public const int routeNameTextView = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int stationDetailsRow = 2131099648;
			
			// aapt resource value: 0x7f060014
			public const int txtLastUpdated = 2131099668;
			
			// aapt resource value: 0x7f060012
			public const int txtMainWithoutStatonsWarningMessage = 2131099666;
			
			// aapt resource value: 0x7f060004
			public const int txtStationId = 2131099652;
			
			// aapt resource value: 0x7f06000c
			public const int txtStationIdentifier = 2131099660;
			
			// aapt resource value: 0x7f060003
			public const int txtStationNick = 2131099651;
			
			// aapt resource value: 0x7f06000e
			public const int txtViewMegalloElnevezese = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int txtViewMegalloHozzadasa = 2131099659;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ListViewRowMainScreen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListViewRowStationDetails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MenuMainScreenActionMenu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ScreenAddFavorite = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ScreenMain = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ScreenMainNoFavorites = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ScreenRouteDetails = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
